
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/core_banking_db
    username: root
    password: JBuckets@13
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

application:
  jwt:
    secretKey: BTD7LXGaPGYXaCVHO5nFstFJwGQGMi6vzQ81U+Gu0sDNpbWI+RrNYYMAcT6PaBEh
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 1
